[features]
seeds = false
skip-lint = false
[programs.devnet]
learnup_program = "ENdQMhEY4G3mEMz9yFAVCV2aRJW4VVeqX1VeX2X3iZzP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/valter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
